export const UPDATABLE_TASK_FIELDS = [
  "title",
  "description",
  "column",
  "sprint",
  "assignee",
  "watchers",
  "status",
  "priority",
  "tags",
  "dueDate",
  "estimatedHours",
  "actualHours",
  "subtasks",
  "isArchived",
] as const;
